apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{values.component_id}}
  description: ${{values.description}}

  annotations:
    github.com/project-slug: osinfra/${{values.destination}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - opentofu-child-module
    - infrastructure-as-code
    - google-cloud-platform

spec:
  type: library
  lifecycle: experimental
  owner: ${{values.owner}}
